# SPDX-License-Identifier: LicenseRef-OQL-1.3
name = "nameless-telemetry"
main = "worker.js"
compatibility_date = "2024-10-01"
workers_dev = false
send_metrics = false
routes = [
  { pattern = "telemetry.namelessnanashi.dev/*", zone_name = "namelessnanashi.dev" },
  { pattern = "census.namelessnanashi.dev/*", zone_name = "namelessnanashi.dev" }
]

[[kv_namespaces]]
binding = "TELEMETRY"
id = "c84deb2f62574d3bb1e54a41522e2d95"

[observability]
enabled = false

[placement]
mode = "smart"