# This software is licensed under NNCL v1.3 see LICENSE.md for more info
name = "nameless-telemetry"
main = "worker.js"
compatibility_date = "2026-01-20"
workers_dev = false
send_metrics = false

routes = [
  { pattern = "telemetry.namelessnanashi.dev/*", zone_name = "namelessnanashi.dev" },
  { pattern = "census.namelessnanashi.dev/*", zone_name = "namelessnanashi.dev" }
]

[[kv_namespaces]]
binding = "TELEMETRY"
id = "c84deb2f62574d3bb1e54a41522e2d95"

[observability]
enabled = false

[placement]
mode = "smart"
