# This software is licensed under NNCL v1.3 see LICENSE.md for more info
name = "nameless-telemetry"
main = "worker.js"
compatibility_date = "2024-10-01"
workers_dev = false
send_metrics = false
routes = [
  { pattern = "telemetry.namelessnanashi.dev/*", zone_name = "namelessnanashi.dev" },
  { pattern = "census.namelessnanashi.dev/*", zone_name = "namelessnanashi.dev" }
]

[[kv_namespaces]]
binding = "TELEMETRY"
id = "${TELEMETRY_KV_ID}"

[observability]
enabled = false

[placement]
mode = "smart"